POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

# PATCH http://localhost:3000/products/5
# Content-Type: application/json

# {
#   "name": "a chair",
#   "price": 22,
#   "image_url": null,
#   "description": null
# }



# DELETE http://localhost:3000/products/3