GET http://localhost:3000/products/1
# Content-Type: application/json

# {
#   "name": "not-maybe-a-chair",
#   "price": 33,
#   "image_url": "not-here.jpg",
#   "description": "definitely not a chair"
# }

# PATCH http://localhost:3000/products/4
# Content-Type: application/json

# {
#   "name": "a chair",
#   "price": null,
#   "image_url": null,
#   "description": null
# }
# DELETE http://localhost:3000/products/3