GET http://localhost:3000/products.json
# Content-Type: application/json

# {
#   "name": "not-that-chair",
#   "price": 13,
#   "image_url": "not-here.jpg",
#   "description": "definitely not a chair",
#   "stock": 2
# }

PATCH http://localhost:3000/products/5
Content-Type: application/json

{
  "name": "a chair",
  "price": 22,
  "image_url": null,
  "description": null
}



# DELETE http://localhost:3000/products/3